# Generated by Django 2.1.7 on 2019-04-13 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendship',
            name='friend',
        ),
        migrations.AddField(
            model_name='jnghner',
            name='friends',
            field=models.ManyToManyField(related_name='_jnghner_friends_+', to='app_user.Jnghner'),
        ),
        migrations.DeleteModel(
            name='FriendShip',
        ),
    ]
