# Generated by Django 2.1.7 on 2019-04-20 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0002_auto_20190413_1743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jnghner',
            name='friends',
        ),
        migrations.AddField(
            model_name='jnghner',
            name='friend',
            field=models.ManyToManyField(related_name='_jnghner_friend_+', to='app_user.Jnghner'),
        ),
    ]
