# Generated by Django 2.1.7 on 2019-04-24 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0004_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='read',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
