# Generated by Django 2.1.7 on 2019-04-24 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0005_message_read'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='message',
            name='read',
        ),
        migrations.AddField(
            model_name='unread',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_user.Message'),
        ),
    ]
