# Generated by Django 2.1.7 on 2019-02-26 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_plan', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detail',
            old_name='place',
            new_name='times',
        ),
    ]
