# Generated by Django 2.1.7 on 2019-03-03 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_plan', '0003_auto_20190303_1614'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentplan',
            old_name='user',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='heartplan',
            old_name='user',
            new_name='author',
        ),
    ]
