# Generated by Django 2.1.7 on 2019-03-16 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_plan', '0004_auto_20190303_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='lock',
            field=models.CharField(default='False', max_length=10),
        ),
    ]
