# Generated by Django 2.1.7 on 2019-03-18 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_plan', '0006_auto_20190316_1706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='lock',
        ),
        migrations.AddField(
            model_name='plan',
            name='password',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
