# Generated by Django 2.1.7 on 2019-03-03 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Army',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graduate', models.TextField()),
                ('period_from', models.DateField()),
                ('period_to', models.DateField()),
                ('position', models.CharField(max_length=100)),
                ('me', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_admin.Me')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('period_from', models.DateField()),
                ('period_to', models.DateField()),
                ('graduate', models.TextField()),
                ('me', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_admin.Me')),
            ],
        ),
        migrations.RenameField(
            model_name='attachment',
            old_name='archive',
            new_name='me',
        ),
        migrations.RenameField(
            model_name='experience',
            old_name='category',
            new_name='title',
        ),
    ]
